#!/bin/sh
#

# update files for cmd/devops with packr 
devopsDir=$(git rev-parse --show-toplevel)/cmd/devops
echo "updating pack files for cmd/devops"
curDir=$PWD
cd $devopsDir 

packr2

cd $curDir 

git add cmd/devops/packrd

fileChanged=$(git diff cmd/devops/packrd)
if [[ $fileChanged != "" ]]; then
	git add cmd/devops/packrd/*
	git commit --amend -C HEAD  --no-verify
fi 

